### PR TITLE
Added log file permissions

### PR DESCRIPTION
**Pull request by jdayamx**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by marcovtwout** [comment]
@jdayamx Thanks for your PR. Yii 1 is in maintainance mode, but if it can be added in a backwards compatible manner we can consider it for merging.

This PR is currently backward incompatible. Default behavior relies on system settings (such as umask) to set permissions. This PR overwrites that with 0644.

Take a look at the implementation done by Yii 2 for `$fileMode`: https://github.com/yiisoft/yii2/blob/master/framework/log/FileTarget.php - if you apply behavior and documentation exactly like that I'll be happy to merge it.

**Comment by jdayamx** [comment]
I got such a situation that the console script and the application were launched under different users, but there was  hase one group, and when the file was created by one user, the second could not write anything to the log. For the file system and working with files, developers should be able to manage file permissions without crutches with inheritance.

**Comment by marcovtwout** [comment]
The PR in its current form still sets default file permissions and this breaks backwards compatibility. Take a closer look at the Yii 2 implementation mentioned above if you would like to get this merged.

**Review by marcovtwout — APPROVED** [review]

**Comment by marcovtwout** [comment]
Update documentation a bit and added changelog entry. Merged, thanks for your contribution!

**Pull request merged**
