### PR TITLE
Param fix

### PR DESCRIPTION
**Pull request by olleharstedt**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | Param issue in function docblock

### CODE REVIEW

**Comment by olleharstedt** [comment]
`itemAt` accepts `mixed`, so this change makes sense.

**Comment by marcovtwout** [comment]
The class implements https://www.php.net/manual/en/class.arrayaccess.php which by now defines the param as `$mixed`. Is this the excepion in the source code or are there more similar changes to be made?

**Comment by olleharstedt** [comment]
> The class implements https://www.php.net/manual/en/class.arrayaccess.php which by now defines the param as `$mixed`. Is this the excepion in the source code or are there more similar changes to be made?

No idea, honestly. Want me to grep around for array access interface?

**Comment by olleharstedt** [comment]
Pushed some more fixes. Skipped CCache, since it's only accepting `string`.

**Comment by olleharstedt** [comment]
@marcovtwout This can be merged :)

**Review by samdark — APPROVED** [review]

**Pull request merged**
