### PR TITLE
zh_cn guide

### PR DESCRIPTION
**Pull request by wxs77577**

### CODE REVIEW

**Comment by cebe** [comment]
Thanks!

**Comment by samdark** [comment]
@cebe it's not fully translated.

**Comment by cebe** [comment]
@wxs77577 are you going to translate more of it? please send a new pull request if done.

**Comment by wxs77577** [comment]
Hi @cebe ,  I need more time to finish the file. `docs/guide/zh_cn/basics.best-practices.txt`

**Comment by cebe** [comment]
sure, take your time.

**Pull request merged**
