### PR TITLE
Added the ability to make the Redis cache connection optional

### PR DESCRIPTION
**Pull request by wisc**
When Yii fails to connect to Redis, it may not need to crash into a 500. The caching may be optional, as it would speed things up, but would not be required for the app to run. In that case a thrown exception is a bit hash.

This update creates a setting that lets the user toggle the behavior, defaulting to what it does now.

### CODE REVIEW

**Comment by cebe** [comment]
You can do this in your application if you want to skip it but I think this is nothing we want to have in the framework itself. Thanks for suggesting though.

**Comment by wisc** [comment]
I don't see how I can skip this in my application. As soon as I set the cache to Redis, Yii will use it internally. So before any of my own code runs, the cache is already accessed by Yii internals. Thus I get a 500 without being able to do anything about it.

**Comment by cebe** [comment]
You can override connect() like the following:

```php
protected function connect()
{
    try {
        parent::connect();
    } catch (CException $e) {
	Yii::app()->setComponent('cache', new CDummyCache);
        Yii::log('redis failed to connect: ' . $e->getMessage(), CLogger::LEVEL_ERROR);
    }

}
```

**Comment by wisc** [comment]
Ah yes. Not a very elegant solution, but I guess there's little choice in the matter.

**Pull request closed without merging**
