### PR TITLE
1.1.15 branch

### PR DESCRIPTION
**Pull request by adrianet86**

### CODE REVIEW

**Comment by samdark** [comment]
Can you merge 1.1.17?

**Comment by cebe** [comment]
this pull request looks broken, it asks to merge `1.1.15-branch` into master?

**Comment by cebe** [comment]
@adrianet86 please open a new one with the changes from a branch in your fork.

**Comment by cebe** [comment]
solved by cherry-picking the wrongly merged commit from #3910 to master.

**Pull request closed without merging**
