### PR TITLE
Optimize PNG files

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
by calling `for i in $(find -name '*.png'); do optipng -o7 -zm9 $i; done`.

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks.

**Comment by marcovtwout** [comment]
@dilyanpalauzov Could you tell me why we would not use the officially distributed files and optimize these?

**Comment by samdark** [comment]
@marcovtwout just these are a bit smaller :) I did that in the past but it was lost during one of the updates.

**Comment by marcovtwout** [comment]
@samdark Thanks for clearning that up. One might otherwise wonder why vendor files are modified / will give a binary signature mismatch. To save just a few hundred bytes I would personally use the originals, but if this was common practice before in yii1 I guess it makes sense.

**Comment by dilyanpalauzov** [comment]
I optimized the PNG files in Limesurvey.  Then I was told that once upstream synchronization happens, the changes will be reverted.  In turn I optimized the PNG files used upstream projects, like here or https://github.com/jquery/jquery-ui/pull/2132.

**Pull request merged**
