### PR TITLE
Rebuild yiiListView to match methodology from yiiGridView

### PR DESCRIPTION
**Pull request by armano2**
Implement new  call $.fn.yiiListView(func)
Correct issue with multiple registering of handlers by binding unbinding old once.

### CODE REVIEW

**Comment by cebe** [comment]
Can you explain these changes in more detail?

for better review without whitespace changes: https://github.com/yiisoft/yii/pull/4088/files?w=0

**Comment by armano2** [comment]
@cebe Can you tell which part?
All changes to yiiListView are basicly compatibility changes made in 1.1.9 for yiiGridView, and now we can use again same syntax for both...

also i'm slowly working to fix (old) issue with grid view inside list view and binding pagination elements for both objects, its just first step.

**Comment by samdark** [comment]
Are these changes incompatible with previous releases?

**Comment by armano2** [comment]
no, everythink is compatible with previous releases but old functions are marked as deprecated now.

$.fn.yiiListView.getKey
$.fn.yiiListView.getUrl
$.fn.yiiListView.update

**Comment by samdark** [comment]
OK. @cebe do you have a project using these extensively to check it?

**Comment by cebe** [comment]
> @cebe do you have a project using these extensively to check it?

no, I can not check it.

**Comment by samdark** [comment]
@armano2 can you gather more interested developers to check it?

**Comment by armano2** [comment]
@samdark i'm already using those changes in 6 live websites

**Comment by samdark** [comment]
Other people usage could be very different.

**Comment by samdark** [comment]
Closing since we can't verify it, there are no interested parties and Yii 1.1 isn't accepting enhancements anymore. Thanks for contribution anyway.

**Pull request closed without merging**
