### PR TITLE
Make composer package lighter

### PR DESCRIPTION
**Pull request by b1rdex**
No one needs demos and concatenated stuff through composer.

### CODE REVIEW

**Comment by samdark** [comment]
Agree about demos but don't agree about the rest.

**Comment by b1rdex** [comment]
Ok, let's remove just demos.

**Comment by samdark** [comment]
Thanks!

**Comment by b1rdex** [comment]
@samdark what do you think about removing `build`, `docs` and `tests` folders aswell? Almost 10MB.

**Comment by samdark** [comment]
They are already removed via `.gitattributes`: https://github.com/yiisoft/yii/blob/master/.gitattributes

**Pull request merged**
