### PR TITLE
Crud generation composite primary key

### PR DESCRIPTION
**Pull request by edisnake**
Hi with this changes yii will can generate crud code for database tables with composite primary keys, checked it out

### CODE REVIEW

**Comment by samdark** [comment]
Can't be merged as is and it seems it's not going anywhere. Closing.

**Comment by teo1978** [comment]
So, there have been 3 pull requests attempting to offer support for CRUD for composite primary keys (a functionality whose lack has always been astonishing in the first place), all have been closed without success, and we still don't have CRUD for composite primary keys? Do I understand the situation correctly?

**Comment by samdark** [comment]
@teo1978 something like that. Do you want to try?

**Comment by teo1978** [comment]
I don't think so.
Has it at least been implemented in Yii2?

**Comment by samdark** [comment]
Try it.

**Comment by nineinchnick** [comment]
I added support for it in Yii2 in my custom gii generator, it requires methods to encode the pk values as strings.

**Comment by cebe** [comment]
Yii2 gii has it implemented.

**Pull request closed without merging**
