### PR TITLE
update topics.auth

### PR DESCRIPTION
**Pull request by wxs77577**
update topics.auth

### CODE REVIEW

**Comment by samdark** [comment]
Thanks!

**Comment by wxs77577** [comment]
hi,when the content in [http://www.yiiframework.com/doc/guide/1.1/zh_cn/topics.auth](http://www.yiiframework.com/doc/guide/1.1/zh_cn/topics.auth) will be changed?

**Comment by samdark** [comment]
With the next release of 1.1 as far as I remember.

**Comment by cebe** [comment]
> With the next release of 1.1 as far as I remember.

yes

**Pull request merged**
