### PR TITLE
php 8.1 support

### PR DESCRIPTION
**Pull request by ac-dc**
PHP8.1 Fix
Fixes errors, like this one
`Return type of CListIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️

### CODE REVIEW

**Comment by marcovtwout** [comment]
I'd like to list all issues in https://github.com/yiisoft/yii/issues/4385 and then fix them in https://github.com/yiisoft/yii/pull/4386

**Comment by samdark** [comment]
@marcovtwout you can change the base of the PR to point to 8.1 fix branch (I just did) then merge it. We did so with Yii2.

**Comment by marcovtwout** [comment]
@samdark Thanks for the tip, but I'm planning to be selective in applying the changes consistently, to prevent a huge list of incremental partial fixes.

**Comment by samdark** [comment]
You can squash it when merging to master.

**Comment by marcovtwout** [comment]
@schiorean See https://github.com/yiisoft/yii/issues/4385#issuecomment-1064048315

**Comment by marcovtwout** [comment]
Superceded by https://github.com/yiisoft/yii/pull/4386#commits-pushed-7de378e

**Pull request closed without merging**
