### PR TITLE
PHP 8.1 support

### PR DESCRIPTION
**Pull request by marcovtwout**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #4385

List of issues:
- [x] Fix tests on Composer v2 and PHP 8.0+ through https://github.com/yiisoft/phpunit-patches/pull/8
- [X] Return type of (..) should either be compatible with (..) void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice (https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.core.type-compatibility-internal)
- [x] Various cases of https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.null-not-nullable-internal
- [x] Various cases of https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.implicit-float-conversion
- [x] Wait for HTMLPurifier PHP 8.1 support in next release 4.15.0 https://github.com/ezyang/htmlpurifier/issues/311 / https://github.com/ezyang/htmlpurifier/pull/310
- [X] PHP 8.1 Cast decimals to string on sqlite https://github.com/yiisoft/yii2/issues/19144

Please list additional issues found in https://github.com/yiisoft/yii/issues/4385

### CODE REVIEW

**Comment by kenguest** [comment]
Support for PHP 8.1 would be great. 
Currently seeing a lot of deprecation messages such as this:
`Return type of CCache::offsetExists($id) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice (/var/www/myproject/vendor/yiisoft/yii/framework/caching/CCache.php:337`

**Comment by mashb1t** [comment]
@marcovtwout as the only checkbox left mentions https://github.com/ezyang/htmlpurifier/issues/311, which was fixed by https://github.com/ezyang/htmlpurifier/pull/310 but not closed, i assume this PR is not blocked anymore. It would be great if you could confirm and merge this PR so we can use Yii with PHP 8.1, thanks!

**Comment by marcovtwout** [comment]
@mashb1t Still waiting on a tagged release for htmlpurifier (https://github.com/ezyang/htmlpurifier/issues/311#issuecomment-1113136007), so I can then incorporate it into this PR and finish it.

**Comment by marcovtwout** [comment]
Since there is no stable release for htmlpurifier with 8.1 support I created a manual build of the appropiate dev version. If someone would like to verify it works I will merge this PR!

**Comment by marcovtwout** [comment]
There finally is a new tagged htmlpurifier release, I'll add that before next release.

**Comment by marcovtwout** [comment]
Htmlpurifier 4.15.0 added to master.

**Pull request merged**
