### PR TITLE
fix/static method getCanonicalID should not be called dynamically

### PR DESCRIPTION
**Pull request by apphp**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Tests pass?   | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Review by marcovtwout — APPROVED** [review]

**Comment by marcovtwout** [comment]
Thanks!

**Comment by rob006** [comment]
This change breaks BC: previously if you extend this class and override `getCanonicalID()`, new implementation was used everywhere. After this change new implementation will be ignored and always `CLocale::getCanonicalID()` will be used.

**Comment by marcovtwout** [comment]
@rob006 Thank you for checking in detail, but that is not exactly the case. The method itself was not updated and was already static, and there are more function calls within the framework that were already calling it correctly using `::getCanonicalID()`

**Comment by rob006** [comment]
@marcovtwout 

Before change: https://3v4l.org/ZAIWn
After change: https://3v4l.org/bM5Ka

I'm not sure if overwriting `getCanonicalID()` is even supported, but `$this->` could be used here to emulate `static::` which was not available in older versions of PHP.

**Comment by marcovtwout** [comment]
The old behavior (to my surprise) doesn't cause any PHP warning. Looking at the history, it doesn't look like $this was used on purpose, so I would say this change is fairly safe.

**Pull request merged**
