### PR TITLE
Allow absolute URLs to start with '//' instead of just 'http' - e.g. …

### PR DESCRIPTION
**Pull request by ksowa**
…'//google.com' is valid absolute URL

### CODE REVIEW

**Comment by ksowa** [comment]
I ran into that issue with my project. For console application I defined 
`$_SERVER['SERVER_NAME'] = '//domain.com';`
for absolute URLs creation - e.g. for activation emails or internal messages system, as we allow both HTTP and HTTPS URLs. The '//' works with all protocols. 

With current Yii I ended up with http:////domain.com//domain.com/path 

With the commit I made it will properly create //domain.com/path URL.

**Comment by samdark** [comment]
Makes sense. Could you add a line for changelog?

**Comment by ksowa** [comment]
Added.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
