### PR TITLE
Fixed  #3974: Array in route parameter

### LINKED ISSUE #3974: Array in route parameter
Version: 1.* 
Request /?r[]=site/index  
Will return warning "trim() expects parameter 1 to be string, array given"

### PR DESCRIPTION
**Pull request by cmazx**

### CODE REVIEW

**Comment by cmazx** [comment]
Have no write access to merge request.
https://github.com/yiisoft/yii/pull/3975
(there no changelog)

**Comment by samdark** [comment]
Commit to the same branch ;)

**Comment by cmazx** [comment]
Done ;)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii/commit/8c9b5114db3ee524d23e985c637b52f329ca5bda. Thanks!

**Pull request closed without merging**
