### PR TITLE
Remove script type attribute

### PR DESCRIPTION
**Pull request by marcovtwout**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️/❌?
| Tests pass?   | ✔️
| Fixed issues  | #4349

### CODE REVIEW

**Comment by rob006** [comment]
Shouldn't this be configurable? In the same way as `Html::$closeSingleTags` and similar flags?

**Comment by marcovtwout** [comment]
@rob006 Did not know about those flags, but that is an option. It would be a bit harder to implemented since Yii also uses hardcoded view files that include this attribute.

I just noticed the previous XHTML standard still requires the type attribute, so I guess we have to at least keep it for backwards compatibility.

**Comment by rob006** [comment]
> It would be a bit harder to implemented since Yii also uses hardcoded view files that include this attribute.

If they have doctype defined as XHTML, it should not be changed. Other partial views seems to be debug-related, so I wouldn't bother to change these. In general I would not change anything except `CHtml`, and maybe `CWebLogRoute` to use `CHtml::script()` to inherit settings from helper.

There is also `/*<![CDATA[*/` which seems to be redundant in HTML5.

**Comment by marcovtwout** [comment]
Closing this PR in favor of https://github.com/yiisoft/yii/pull/4351

**Pull request closed without merging**
